<a href="https://colab.research.google.com/github/Shashwot90/objectdetection/blob/main/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([2,0,-3,8,90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [4]:
tensor_four_d = tf.constant([
   [
      [[13,23,4],
     [2,3,4]],
      [[13,23,4],
     [2,3,4]]
   ] ,
   [
      [[13,23,4],
     [2,3,4]],
      [[13,23,4],
     [2,3,4]]
   ]
])

In [5]:
print(tensor_four_d)

tf.Tensor(
[[[[13 23  4]
   [ 2  3  4]]

  [[13 23  4]
   [ 2  3  4]]]


 [[[13 23  4]
   [ 2  3  4]]

  [[13 23  4]
   [ 2  3  4]]]], shape=(2, 2, 2, 3), dtype=int32)


In [7]:
import numpy as np

In [8]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]
